// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A placeholder FirebaseOptions for use during development.
/// Once you have set up a Firebase project, update these with your project details.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxyXfNE0A45lhC5XcdqAEeiHL759HQbI',
    appId: '1:600579336774:ios:placeholder1234567890',
    messagingSenderId: '600579336774',
    projectId: 'cycle-sync-mvp-820b2',
    storageBucket: 'cycle-sync-mvp-820b2.firebasestorage.app',
    iosBundleId: 'com.example.cycleSyncMvp2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxyXfNE0A45lhC5XcdqAEeiHL759HQbI',
    appId: '1:600579336774:android:ca4ddc9447740b29b53847',
    messagingSenderId: '600579336774',
    projectId: 'cycle-sync-mvp-820b2',
    storageBucket: 'cycle-sync-mvp-820b2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxyXfNE0A45lhC5XcdqAEeiHL759HQbI',
    appId: '1:600579336774:web:placeholder1234567890',
    messagingSenderId: '600579336774',
    projectId: 'cycle-sync-mvp-820b2',
    storageBucket: 'cycle-sync-mvp-820b2.firebasestorage.app',
  );
}
